# Generated by Django 4.1 on 2022-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Order number")),
                ("price_in_usd", models.IntegerField(verbose_name="Price in USD")),
                ("price_in_rub", models.IntegerField(verbose_name="Price in RUB")),
                ("delivery_date", models.DateField()),
            ],
        ),
    ]
